### ISSUE TITLE
Chápem to správne, že API si mám napísať sám?

### ISSUE THREAD

**Issue by camohub** [Trejjam/MailChimp#1]
Chápem to správne, že API si mám napísať sám? Žiadna trieda s metódou subscribe/unsubscribe tu nieje.

**Comment by Trejjam** [comment]
Pekny den,

my jsme zvolili jine, neni psane pro Nette a vyuziva starsi MailChimp API.

Myslenka hezciho a aktualizovaniho API se nam libila, ale nebyl na ni cas.

J

**Comment by camohub** [comment]
Tak ako sa to vlastne používa? Jeto funkčné? Čo znamenajú ... v zápise ```\Trejjam\MailChimp\...```

**Comment by Trejjam** [comment]
Je to jen template knihovny, kterou jsem nechtěl odepsat, ale čas (a potřebu) na její dopsání jsem nenašel.

V tuto chvíli v ní spásu hotového řešení nenajdete. Můžete se podívat po jiné knihovně.

`Trejjam\MailChimp\...` je opět template, když se podíváte do src zjistíte, že existuje pouze třída `DI\MailChimpExtension.php`, která nic neregistruje, jen validuje očekávanou konfigurace. A má na všech podstatných místech `TODO`

**Comment by Trejjam** [comment]
BTW titulek `[In progress] MailChimp client for Nette` by mohl lecos napovědět...

**Comment by camohub** [comment]
Kde je ten titulok? A čo to teda robí na Packagiste ak to nefunguje?

**Comment by Trejjam** [comment]
![snimek z 2016-11-29 12-37-28](https://cloud.githubusercontent.com/assets/3594540/20708566/c51be8ee-b630-11e6-9a3a-ca7a3b85964f.png)

Na Packagistu je proto aby zamýšlený vývoj byl možný. Jen na něj nebyl čas

**Comment by Trejjam** [comment]
![snimek z 2016-11-29 12-48-40](https://cloud.githubusercontent.com/assets/3594540/20708860/38824048-b632-11e6-9e54-8e7ac8e1f5df.png)

**Comment by camohub** [comment]
Zamýšľaný vývoj sa robí na Githube. Na packagist patria hotové funkčné veci aby ste nemiatli ľudí.

**Comment by Trejjam** [comment]
Lidé obvykle čtou
